clc;
clear all; 
close all; 
fc=25;
fs = 1000;
t=0:1/fs:1-1/fs; 
x=square(2*pi*fc*t)+1;
subplot(3,1,1);
plot(x);
title('PULSE TRAIN');
xlabel('TIME') ;
ylabel('AMPLITUDE');
grid on;
p=length(x);
q = fft(x);
subplot(3,1,2);
plot(abs(q));
title('FFT');
xlabel('TIME') ;
ylabel('AMPLITUDE');
grid on;
q = q(1:p/2+1); 
s = (1/(fs*p)) * abs(q).^2;
s(2:end-1) = 2*s(2:end-1);
frequency= 0:fs/length(x):fs/2;
subplot(3,1,3); 
plot(frequency, 10*log10(s));
grid on;
title('POWER SPECTRAL DENSITY OF PULSE TRAIN');
xlabel('FREQUENCY');
ylabel('AMPLITUDE');