clc;
clear all; 
close all; 
fc=25;
fs = 100;
t1=-1:0.01:0;
t2=0:0.01:1;
t3=1:0.01:2;
x1=zeros(size(t1));
x2=ones(size(t2));
x3=zeros(size(t3));
x=[x1 x2 x3];
subplot(3,1,1);
plot(x);
title('PULSE TRAIN');
xlabel('TIME') ;
ylabel('AMPLITUDE');
grid on;
p=length(x);
q = fft(x);
subplot(3,1,2);
plot(abs(q));
title('FFT');
xlabel('TIME') ;
ylabel('AMPLITUDE');
grid on;
q =q(1:p/2+1); 
s = (1/(fs*p))*abs(q).^2;
s(2:end-1) = 2*s(2:end-1);
frequency= 0:fs/length(x):fs/2;
subplot(3,1,3); 
plot(frequency, 10*log10(s));
grid on;
title('POWER SPECTRAL DENSITY OF PULSE TRAIN');
xlabel('FREQUENCY');
ylabel('AMPLITUDE');